export const countries = [
  {
    name: "Argentina",
    code: "AR",
    phoneFormat: "+54 NN NNNN-NNNN",
    phoneRegExp: "^\\+54 [0-9]{2} [0-9]{4}-[0-9]{4}$",
  },
  {
    name: "Argentina",
    code: "AR",
    phoneFormat: "+54 NNNN NNNN NNNN",
    phoneRegExp: "^\\+54 [0-9]{4} [0-9]{4} [0-9]{4}$",
  },
  {
    name: "Australia",
    code: "AU",
    phoneFormat: "+61 NNN NNN NNN",
    phoneRegExp: "^\\+61 [0-9]{3} [0-9]{3} [0-9]{3}$",
  },
  {
    name: "Austria",
    code: "AT",
    phoneFormat: "+43 NNNN NNNNNN",
    phoneRegExp: "^\\+43 [0-9]{4} [0-9]{6}$",
  },
  {
    name: "Austria",
    code: "AT",
    phoneFormat: "+43 NNN NNNNNNN",
    phoneRegExp: "^\\+43 [0-9]{3} [0-9]{6,7}$",
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    phoneFormat: "+994 NNN NNN NN NN",
    phoneRegExp: "^\\+994 [0-9]{3} [0-9]{2} [0-9]{2} [0-9]{2}$",
  },
  {
    name: "Bahamas",
    code: "BS",
    phoneFormat: "+1 (NNN) NNN-NNNN",
    phoneRegExp: "^\\+1 ([0-9]{3}) [0-9]{3}-[0-9]{4}$",
  },
  {
    name: "Belgium",
    code: "BE",
    phoneFormat: "+32 NNNN NNN NNN",
    phoneRegExp: "^\\+32 [0-9]{4} [0-9]{3} [0-9]{3}$",
  },
  {
    name: "Belgium",
    code: "BE",
    phoneFormat: "+32 NNNN NN NN NN",
    phoneRegExp: "^\\+32 [0-9]{4} [0-9]{2} [0-9]{2} [0-9]{2}$",
  },
  {
    name: "Brazil",
    code: "BR",
    phoneFormat: "+55 NNNNN-NNNN",
    phoneRegExp: "^\\+55 [0-9]{5}-[0-9]{4}$",
  },
  {
    name: "Brazil",
    code: "BR",
    phoneFormat: "+55 NNNN NNNN NNNN",
    phoneRegExp: "^\\+55 [0-9]{4} [0-9]{4} [0-9]{4}$",
  },
  {
    name: "Canada",
    code: "CA",
    phoneFormat: "+1 (NNN) NNN-NNNN",
    phoneRegExp: "^\\+1 ([0-9]{3}) [0-9]{3}-[0-9]{4}$",
  },
  {
    name: "Chile",
    code: "CL",
    phoneFormat: "+56 NNNN NNNN NNNN",
    phoneRegExp: "^\\+56 [0-9]{4} [0-9]{4} [0-9]{4}$",
  },
  {
    name: "China",
    code: "CN",
    phoneFormat: "+86 NNN-NNNN-NNNN",
    phoneRegExp: "^\\+86 [0-9]{3}-[0-9]{4}-[0-9]{4}$",
  },
  {
    name: "Colombia",
    code: "CO",
    phoneFormat: "+57 NNN NNNNNNN",
    phoneRegExp: "^\\+57 [0-9]{3} [0-9]{6,7}$",
  },
  {
    name: "Colombia",
    code: "CO",
    phoneFormat: "+57 NNN NNNNNNN",
    phoneRegExp: "^\\+57 [0-9]{3} [0-9]{6,7}$",
  },
  {
    name: "Croatia",
    code: "HR",
    phoneFormat: "+385 NNN NNN NNN",
    phoneRegExp: "^\\+385 [0-9]{3} [0-9]{3} [0-9]{3}$",
  },
  {
    name: "Czech Republic",
    code: "CZ",
    phoneFormat: "+420 NNN NNN NNN",
    phoneRegExp: "^\\+420 [0-9]{3} [0-9]{3} [0-9]{3}$",
  },
  {
    name: "Denmark",
    code: "DK",
    phoneFormat: "+45 NNNN NNNN",
    phoneRegExp: "^\\+45 [0-9]{4} [0-9]{4}$",
  },
  {
    name: "Denmark",
    code: "DK",
    phoneFormat: "+45 NNNN NNNN",
    phoneRegExp: "^\\+45 [0-9]{4} [0-9]{4}$",
  },
  {
    name: "Ecuador",
    code: "EC",
    phoneFormat: "+593 NNN NNN NNNN",
    phoneRegExp: "^\\+593 [0-9]{3} [0-9]{3} [0-9]{4}$",
  },
  {
    name: "Egypt",
    code: "EG",
    phoneFormat: "+20 NNNN NNN NNNN",
    phoneRegExp: "^\\+20 [0-9]{4} [0-9]{3} [0-9]{4}$",
  },
  {
    name: "Egypt",
    code: "EG",
    phoneFormat: "+20 NNNN NNNN NNNN",
    phoneRegExp: "^\\+20 [0-9]{4} [0-9]{4} [0-9]{4}$",
  },
  {
    name: "Finland",
    code: "FI",
    phoneFormat: "+358 NNNNNNNN",
    phoneRegExp: "^\\+358 [0-9]{8}$",
  },
  {
    name: "France",
    code: "FR",
    phoneFormat: "+33 N NNNN-NNNN",
    phoneRegExp: "^\\+33 d [0-9]{4}-[0-9]{4}$",
  },
  {
    name: "France",
    code: "FR",
    phoneFormat: "+33 N NN NN NN NN",
    phoneRegExp: "^\\+33 [0-9]{1} [0-9]{2} [0-9]{2} [0-9]{2} [0-9]{2}$",
  },
  {
    name: "Germany",
    code: "DE",
    phoneFormat: "+49 NNNN NNNN NNNN",
    phoneRegExp: "^\\+49 [0-9]{4} [0-9]{4} [0-9]{4}$",
  },
  {
    name: "Greece",
    code: "GR",
    phoneFormat: "+30 NNNN NNNNNN",
    phoneRegExp: "^\\+30 [0-9]{4} [0-9]{6}$",
  },
  {
    name: "Greece",
    code: "GR",
    phoneFormat: "+30 NNNN NNNNNN",
    phoneRegExp: "^\\+30 [0-9]{4} [0-9]{6}$",
  },
  {
    name: "Hong Kong",
    code: "HK",
    phoneFormat: "+852 NNNN NNNN",
    phoneRegExp: "^\\+852 [0-9]{4} [0-9]{4}$",
  },
  {
    name: "Hong Kong",
    code: "HK",
    phoneFormat: "+852 NNNN NNNN",
    phoneRegExp: "^\\+852 [0-9]{4} [0-9]{4}$",
  },
  {
    name: "Hungary",
    code: "HU",
    phoneFormat: "+36 NNN NNN NNNN",
    phoneRegExp: "^\\+36 [0-9]{3} [0-9]{3} [0-9]{4}$",
  },
  {
    name: "Iceland",
    code: "IS",
    phoneFormat: "+354 NNN NNNN",
    phoneRegExp: "^\\+354 [0-9]{3} [0-9]{4}$",
  },
  {
    name: "India",
    code: "IN",
    phoneFormat: "+91 NNNNN NNNNN",
    phoneRegExp: "^\\+91 [0-9]{5} [0-9]{5}$",
  },
  {
    name: "India",
    code: "IN",
    phoneFormat: "+91 NNNNN NNNNNN",
    phoneRegExp: "^\\+91 [0-9]{5} [0-9]{6}$",
  },
  {
    name: "Indonesia",
    code: "ID",
    phoneFormat: "+62 NNNN NNNN NNNN",
    phoneRegExp: "^\\+62 [0-9]{4} [0-9]{4} [0-9]{4}$",
  },
  {
    name: "Indonesia",
    code: "ID",
    phoneFormat: "+62 NNN NNNN NNNN",
    phoneRegExp: "^\\+62 [0-9]{3} [0-9]{4} [0-9]{4}$",
  },
  {
    name: "Iran",
    code: "IR",
    phoneFormat: "+98 NNNN NNN NNNN",
    phoneRegExp: "^\\+98 [0-9]{4} [0-9]{3} [0-9]{4}$",
  },
  {
    name: "Ireland",
    code: "IE",
    phoneFormat: "+353 NNN NNN NNNN",
    phoneRegExp: "^\\+353 [0-9]{3} [0-9]{3} [0-9]{4}$",
  },
  {
    name: "Israel",
    code: "IL",
    phoneFormat: "+972 NN-NNN-NNNN",
    phoneRegExp: "^\\+972 [0-9]{2}-[0-9]{3}-[0-9]{4}$",
  },
  {
    name: "Italy",
    code: "IT",
    phoneFormat: "+39 NNN NNN NNNN",
    phoneRegExp: "^\\+39 [0-9]{3} [0-9]{3} [0-9]{4}$",
  },
  {
    name: "Jamaica",
    code: "JM",
    phoneFormat: "+1 (NNN) NNN-NNNN",
    phoneRegExp: "^\\+1 ([0-9]{3}) [0-9]{3}-[0-9]{4}$",
  },
  {
    name: "Japan",
    code: "JP",
    phoneFormat: "+81 NNN-NNNN-NNNN",
    phoneRegExp: "^\\+81 [0-9]{3}-[0-9]{4}-[0-9]{4}$",
  },
  {
    name: "Kenya",
    code: "KE",
    phoneFormat: "+254 NNN NNN NNNN",
    phoneRegExp: "^\\+254 [0-9]{3} [0-9]{3} [0-9]{4}$",
  },
  {
    name: "Malaysia",
    code: "MY",
    phoneFormat: "+60 NN-NNNN NNNN",
    phoneRegExp: "^\\+60 [0-9]{2}-[0-9]{4} [0-9]{4}$",
  },
  {
    name: "Mexico",
    code: "MX",
    phoneFormat: "+52 NNN NNNN-NNNN",
    phoneRegExp: "^\\+52 [0-9]{3} [0-9]{4}-[0-9]{4}$",
  },
  {
    name: "Morocco",
    code: "MA",
    phoneFormat: "+212 NNN NN NN NN",
    phoneRegExp: "^\\+212 [0-9]{3} [0-9]{2} [0-9]{2} [0-9]{2}$",
  },
  {
    name: "Morocco",
    code: "MA",
    phoneFormat: "+212 NNN NNNNNNN",
    phoneRegExp: "^\\+212 [0-9]{3} [0-9]{6}$",
  },
  {
    name: "Netherlands",
    code: "NL",
    phoneFormat: "+31 NNN NNN NNNN",
    phoneRegExp: "^\\+31 [0-9]{3} [0-9]{3} [0-9]{4}$",
  },
  {
    name: "New Zealand",
    code: "NZ",
    phoneFormat: "+64 NNN NNN NNNN",
    phoneRegExp: "^\\+64 [0-9]{3} [0-9]{3} [0-9]{4}$",
  },
  {
    name: "Nigeria",
    code: "NG",
    phoneFormat: "+234 NNN NNN NNNN",
    phoneRegExp: "^\\+234 [0-9]{3} [0-9]{7}$",
  },
  {
    name: "Nigeria",
    code: "NG",
    phoneFormat: "+234 NNN NNN NNNN",
    phoneRegExp: "^\\+234 [0-9]{3} [0-9]{3} [0-9]{4}$",
  },
  {
    name: "Norway",
    code: "NO",
    phoneFormat: "+47 NNN NN NNN",
    phoneRegExp: "^\\+47 [0-9]{3} [0-9]{2} [0-9]{3}$",
  },
  {
    name: "Pakistan",
    code: "PK",
    phoneFormat: "+92 NNN NNN NNNN",
    phoneRegExp: "^\\+92 [0-9]{3} [0-9]{3} [0-9]{4}$",
  },
  {
    name: "Philippines",
    code: "PH",
    phoneFormat: "+63 NNN NNN NNNN",
    phoneRegExp: "^\\+63 [0-9]{3} [0-9]{3} [0-9]{4}$",
  },
  {
    name: "Poland",
    code: "PL",
    phoneFormat: "+48 NNN NNN NN NN",
    phoneRegExp: "^\\+48 [0-9]{3} [0-9]{3} [0-9]{2} [0-9]{2}$",
  },
  {
    name: "Portugal",
    code: "PT",
    phoneFormat: "+351 NNN NNN NNN",
    phoneRegExp: "^\\+351 [0-9]{3} [0-9]{3} [0-9]{3}$",
  },
  {
    name: "Russia",
    code: "RU",
    phoneFormat: "+7 NNN NNN-NN-NN",
    phoneRegExp: "^\\+7 [0-9]{3} [0-9]{3}-[0-9]{2}-[0-9]{2}$",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    phoneFormat: "+966 NNN NNN NNNN",
    phoneRegExp: "^\\+966 [0-9]{9}$",
  },
  {
    name: "Serbia",
    code: "RS",
    phoneFormat: "+381 NNN NNNNNNN",
    phoneRegExp: "^\\+381 [0-9]{3} [0-9]{6,7}$",
  },
  {
    name: "Singapore",
    code: "SG",
    phoneFormat: "+65 NNNN NNNN",
    phoneRegExp: "^\\+65 [0-9]{4} [0-9]{4}$",
  },
  {
    name: "South Africa",
    code: "ZA",
    phoneFormat: "+27 NNN NNN NNNN",
    phoneRegExp: "^\\+27 [0-9]{3} [0-9]{3} [0-9]{4}$",
  },
  {
    name: "South Korea",
    code: "KR",
    phoneFormat: "+82 NNN NNNN NNNN",
    phoneRegExp: "^\\+82 [0-9]{3} [0-9]{4} [0-9]{4}$",
  },
  {
    name: "Spain",
    code: "ES",
    phoneFormat: "+34 NNN NNN NNN",
    phoneRegExp: "^\\+34 [0-9]{3} [0-9]{3} [0-9]{3}$",
  },
  {
    name: "Sweden",
    code: "SE",
    phoneFormat: "+46 NNN-NNN NN NN",
    phoneRegExp: "^\\+46 [0-9]{3}-[0-9]{3} [0-9]{2} [0-9]{2}$",
  },
  {
    name: "Switzerland",
    code: "CH",
    phoneFormat: "+41 NNN NNN NN NN",
    phoneRegExp: "^\\+41 [0-9]{3} [0-9]{3} [0-9]{2} [0-9]{2}$",
  },
  {
    name: "Switzerland",
    code: "CH",
    phoneFormat: "+41 NNN NNN NN NN",
    phoneRegExp: "^\\+41 [0-9]{3} [0-9]{3} [0-9]{2} [0-9]{2}$",
  },
  {
    name: "Taiwan",
    code: "TW",
    phoneFormat: "+886 NNNN-NNN-NNN",
    phoneRegExp: "^\\+886 [0-9]{4}-[0-9]{3}-[0-9]{3}$",
  },
  {
    name: "Taiwan",
    code: "TW",
    phoneFormat: "+886 NNN NNN NNN",
    phoneRegExp: "^\\+886 [0-9]{3} [0-9]{3} [0-9]{3}$",
  },
  {
    name: "Thailand",
    code: "TH",
    phoneFormat: "+66 NNN NNN NNNN",
    phoneRegExp: "^\\+66 [0-9]{3} [0-9]{3} [0-9]{4}$",
  },
  {
    name: "Tunisia",
    code: "TN",
    phoneFormat: "+216 NNN NNN NNN",
    phoneRegExp: "^\\+216 [0-9]{3} [0-9]{3} [0-9]{3}$",
  },
  {
    name: "Turkey",
    code: "TR",
    phoneFormat: "+90 NNN NNN NN NN",
    phoneRegExp: "^\\+90 [0-9]{3} [0-9]{3} [0-9]{2} [0-9]{2}$",
  },
  {
    name: "Ukraine",
    code: "UA",
    phoneFormat: "+380 NNN NNN NNNN",
    phoneRegExp: "^\\+380 [0-9]{3} [0-9]{3} [0-9]{4}$",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    phoneFormat: "+971 N NNN NNNNN",
    phoneRegExp: "^\\+971 [0-9]{1} [0-9]{3} [0-9]{4}$",
  },
  {
    name: "United Kingdom",
    code: "GB",
    phoneFormat: "+44 NNNN NNNNNN",
    phoneRegExp: "^\\+44 [0-9]{4} [0-9]{6}$",
  },
  {
    name: "United Kingdom",
    code: "GB",
    phoneFormat: "+44 NN NNNN NNNNN",
    phoneRegExp: "^\\+44 [0-9]{2} [0-9]{4} [0-9]{4}$",
  },
  {
    name: "United States",
    code: "US",
    phoneFormat: "+1 (NNN) NNN-NNNN",
    phoneRegExp: "^\\+1 ([0-9]{3}) [0-9]{3}-[0-9]{4}$",
  },
  {
    name: "Venezuela",
    code: "VE",
    phoneFormat: "+58 NNN NNNNNNN",
    phoneRegExp: "^\\+58 [0-9]{3} [0-9]{7}$",
  },
  {
    name: "Vietnam",
    code: "VN",
    phoneFormat: "+84 NNN NNNN NNN",
    phoneRegExp: "^\\+84 [0-9]{3} [0-9]{4} [0-9]{3}$",
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    phoneFormat: "+263 NNN NNN NNNN",
    phoneRegExp: "^\\+263 [0-9]{3} [0-9]{3} [0-9]{4}$",
  },
] as const;
